[package]
name = "cgroup-dev-common"
version = "0.1.0"
edition = "2021"

[features]
default = []
user = ["aya"]

[dependencies]
aya = { git = "https://github.com/bpfdeploy-io/aya", branch = "ml/cgroup-device",  optional = true }

[lib]
path = "src/lib.rs"
